In [79]:
import pandas as pd  #for data preprocessing, cleaning and feature engineering
import numpy as np

In [80]:
# Data collection and Integration
files = [
    "./Dataset/historicalemshourlyload-2019.xlsx",
    "./Dataset/historicalemshourlyload-2020.xlsx",
    "./Dataset/historicalemshourlyload-2021.xlsx",
    "./Dataset/historicalemshourlyload-2022.xlsx",
    "./Dataset/historicalemshourlyloadfor2023.xlsx",
    "./Dataset/historical-ems-hourly-load-for-april-2024.xlsx",
    "./Dataset/historical-ems-hourly-load-for-april-2025.xlsx",
    "./Dataset/historical-ems-hourly-load-for-april-2026.xlsx",
    "./Dataset/historical-ems-hourly-load-for-august-2024.xlsx",
    "./Dataset/historical-ems-hourly-load-for-august-2025.xlsx",
    "./Dataset/historical-ems-hourly-load-for-december-2024.xlsx",
    "./Dataset/historical-ems-hourly-load-for-december-2025.xlsx",
    "./Dataset/historical-ems-hourly-load-for-february-2025.xlsx",
    "./Dataset/historical-ems-hourly-load-for-february-2026.xlsx",
    "./Dataset/historical-ems-hourly-load-for-january-2025.xlsx",
    "./Dataset/historical-ems-hourly-load-for-january-2026.xlsx",
    "./Dataset/historical-ems-hourly-load-for-july-2024.xlsx",
    "./Dataset/historical-ems-hourly-load-for-july-2025.xlsx",
    "./Dataset/historical-ems-hourly-load-for-june-2024.xlsx",
    "./Dataset/historical-ems-hourly-load-for-june-2025.xlsx",
    "./Dataset/historical-ems-hourly-load-for-march-2025.xlsx",
    "./Dataset/historical-ems-hourly-load-for-march-2026.xlsx",
    "./Dataset/historical-ems-hourly-load-for-may-2024.xlsx",
    "./Dataset/historical-ems-hourly-load-for-may-2025.xlsx",
    "./Dataset/historical-ems-hourly-load-for-november-2024.xlsx",
    "./Dataset/historical-ems-hourly-load-for-november-2025.xlsx",
    "./Dataset/historical-ems-hourly-load-for-october-2024.xlsx",
    "./Dataset/historical-ems-hourly-load-for-october-2025.xlsx",
    "./Dataset/historical-ems-hourly-load-for-september-2024.xlsx",
    "./Dataset/historical-ems-hourly-load-for-september-2025.xlsx",
    "./Dataset/historicalemshourlyloadforfebruary2024.xlsx",
    "./Dataset/historicalemshourlyloadforjanuary2024.xlsx",
    "./Dataset/historicalemshourlyloadformarch2024.xlsx"
]

In [81]:
#Merge(conacate) all Electricity consumption data
merged_df = pd.DataFrame()

for file in files:
    df = pd.read_excel(file)
    merged_df = pd.concat([merged_df, df], ignore_index=True)

# Save Merged Data
merged_df.to_excel("./Dataset/Energy_consumption_2019_April2026.xlsx")

print("All files merged succesfully")

All files merged succesfully

In [82]:
# Load weather Data
weather_df = pd.read_excel("./Dataset/weather2019_april2026_california.xlsx")

In [83]:
# Ḍata Inforamtion
print("Merged Info about energy : ")
print(merged_df.info())
print("Weather Data Information - :")
print(weather_df.info())

Merged Info about energy :
<class 'pandas.DataFrame'>
RangeIndex: 64247 entries, 0 to 64246
Data columns (total 12 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   Date                                        64247 non-null  datetime64[us]
 1   HR                                          64247 non-null  int64
 2   PGE                                         64247 non-null  float64
 3   SCE                                         64247 non-null  float64
 4   SDGE                                        64247 non-null  float64
 5   VEA                                         64247 non-null  float64
 6   CAISO Total                                 17544 non-null  float64
 7   Unnamed: 7                                  6 non-null      object
 8   CAISO                                       46703 non-null  float64
 9   Spring DST change occurs on March 9 in HE2  0 non-null      float64
 10  DST change occurs on March 8 at 2AM         0 non-null      float64
 11  Fall DST change occurs on 11/2/2025 at 1am  0 non-null      float64
dtypes: datetime64[us](1), float64(9), int64(1), object(1)
memory usage: 5.9+ MB
None
Weather Data Information - :
<class 'pandas.DataFrame'>
RangeIndex: 64248 entries, 0 to 64247
Data columns (total 3 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Time              64248 non-null  datetime64[us]
 1   Temperature       64248 non-null  float64
 2   RelativeHumidity  64248 non-null  int64
dtypes: datetime64[us](1), float64(1), int64(1)
memory usage: 1.5 MB
None

In [84]:
print("Energy Data : ")
print(merged_df.head())

print("Weather Data :")
print(weather_df.head())

Energy Data :
        Date  HR          PGE          SCE         SDGE         VEA  \
0 2019-01-01   1  9844.620265  9928.001620  2088.453772   92.069996
1 2019-01-01   2  9507.691745  9604.449654  1998.915397   92.659879
2 2019-01-01   3  9251.837855  9340.780790  1934.057172   93.592896
3 2019-01-01   4  9123.916881  9183.897175  1891.808751   97.052299
4 2019-01-01   5  9156.274437  9170.727964  1898.794915  101.469059

    CAISO Total                                         Unnamed: 7  CAISO  \
0  21953.146163  Note: The hourly load value at hour ending (HE...    NaN
1  21203.716174                                                NaN    NaN
2  20620.268525                                                NaN    NaN
3  20296.675172                                                NaN    NaN
4  20327.266153                                                NaN    NaN

   Spring DST change occurs on March 9 in HE2  \
0                                         NaN
1                                         NaN
2                                         NaN
3                                         NaN
4                                         NaN

   DST change occurs on March 8 at 2AM  \
0                                  NaN
1                                  NaN
2                                  NaN
3                                  NaN
4                                  NaN

   Fall DST change occurs on 11/2/2025 at 1am
0                                         NaN
1                                         NaN
2                                         NaN
3                                         NaN
4                                         NaN
Weather Data :
                 Time  Temperature  RelativeHumidity
0 2019-01-01 00:00:00         15.3                49
1 2019-01-01 01:00:00         14.7                49
2 2019-01-01 02:00:00         13.2                55
3 2019-01-01 03:00:00         11.6                51
4 2019-01-01 04:00:00         10.2                38

In [85]:

merged_df["Date"] += pd.to_timedelta(merged_df["HR"] - 1, unit="h") # make DATE col Similar to Weather_df Time Col for merging
merged_df.head()

,Date,HR,PGE,SCE,SDGE,VEA,CAISO Total,Unnamed: 7,CAISO,Spring DST change occurs on March 9 in HE2,DST change occurs on March 8 at 2AM,Fall DST change occurs on 11/2/2025 at 1am
0,2019-01-01 00:00:00,1,9844.620265,9928.001620,2088.453772,92.069996,21953.146163,Note: The hourly load value at hour ending (HE...,NaN,NaN,NaN,NaN
1,2019-01-01 01:00:00,2,9507.691745,9604.449654,1998.915397,92.659879,21203.716174,NaN,NaN,NaN,NaN,NaN
2,2019-01-01 02:00:00,3,9251.837855,9340.780790,1934.057172,93.592896,20620.268525,NaN,NaN,NaN,NaN,NaN
3,2019-01-01 03:00:00,4,9123.916881,9183.897175,1891.808751,97.052299,20296.675172,NaN,NaN,NaN,NaN,NaN
4,2019-01-01 04:00:00,5,9156.274437,9170.727964,1898.794915,101.469059,20327.266153,NaN,NaN,NaN,NaN,NaN

In [89]:
#Internsection of merged_df and weather_df on DATE and TIME col

# Merge
final_df = pd.merge(
    merged_df,
    weather_df,
    left_on="Date",
    right_on="Time",
    how="inner"
)


final_df.head()

,Date,HR,PGE,SCE,SDGE,VEA,CAISO Total,Unnamed: 7,CAISO,Spring DST change occurs on March 9 in HE2,DST change occurs on March 8 at 2AM,Fall DST change occurs on 11/2/2025 at 1am,Time,Temperature,RelativeHumidity
0,2019-01-01 00:00:00,1,9844.620265,9928.001620,2088.453772,92.069996,21953.146163,Note: The hourly load value at hour ending (HE...,NaN,NaN,NaN,NaN,2019-01-01 00:00:00,15.3,49
1,2019-01-01 01:00:00,2,9507.691745,9604.449654,1998.915397,92.659879,21203.716174,NaN,NaN,NaN,NaN,NaN,2019-01-01 01:00:00,14.7,49
2,2019-01-01 02:00:00,3,9251.837855,9340.780790,1934.057172,93.592896,20620.268525,NaN,NaN,NaN,NaN,NaN,2019-01-01 02:00:00,13.2,55
3,2019-01-01 03:00:00,4,9123.916881,9183.897175,1891.808751,97.052299,20296.675172,NaN,NaN,NaN,NaN,NaN,2019-01-01 03:00:00,11.6,51
4,2019-01-01 04:00:00,5,9156.274437,9170.727964,1898.794915,101.469059,20327.266153,NaN,NaN,NaN,NaN,NaN,2019-01-01 04:00:00,10.2,38